heading height fixed.
iiitv/sol pull request #14
Opened 2020-09-01 11:32 UTC by nlok5923

you can see the updated site here : https://cranky-mclean-5f049c.netlify.app/

![Screenshot (1300)](https://user-images.githubusercontent.com/56120084/91844307-11c35c80-ec0c-11ea-8c9f-8cbdcc1aee01.png)

2020-09-02 09:30 UTC, nlok5923 commented
@iiitv/project-maintainers sir please review this pull request.

2020-09-03 17:32 UTC, aashutoshrathi requested changes
Also, activate your Windows 😛

2020-09-03 17:32 UTC, aashutoshrathi commented on style.css
> + .heading-height{
Fix indentation here

2020-09-04 02:14 UTC, nlok5923 commented
@aashutoshrathi Sir requested changes done.

2020-09-05 02:27 UTC, aashutoshrathi approved these changes
LGTM

2020-09-05 02:28 UTC, merged