Made Active Mobile menu
iiitv/sol pull request #16
Opened 2020-09-05 03:10 UTC by The-Keshav-Agarwal

fixes #8 
Updated site: https://zealous-thompson-d415ca.netlify.app/#about

2020-09-06 06:49 UTC, The-Keshav-Agarwal commented
@iiitv/project-maintainers sir please review this pull request.

2020-09-20 17:25 UTC, AmanRaj1608 requested changes

2020-09-20 17:25 UTC, AmanRaj1608 commented on script.js
> +           console.log(`${c.id}, ${window.location.hash} i am in else section `)
Remove the log

2020-09-20 17:33 UTC, AmanRaj1608 approved these changes

2020-09-20 17:33 UTC, merged